### PR TITLE
Note that the driver is for the LSM303DLHC

### LINKED ISSUE #17: Specify this library is for the LSM303DLHC
This library is for the LSM303DLHC and NOT the aLSM303DLH proper.  The two are similar, but the Y and Z orientations for magnetic detection are swapped, so they are incompatible.  Since this library primarily intended for use with the Adafruit devices using the LSM303DLHC, the documentation should specify this driver explicitly where it currently references "LSM303DLH".  This will also help in preventing it from being used with devices using the other.  Thanks @Arduino3128 for helping to bring this to attention!

### PR DESCRIPTION
**Pull request by tekktrik**
Fixes #17

### CODE REVIEW

**Review by jposada202020 — COMMENTED** [review]
Notes are good. Verified the readme.rst in your branch and LGTM. A question tho.. is there any reason that I am not aware that we have the a prefix before the sensor reference as in aLSM303DLH instead of LSM303DLH. Thanks :) maybe there is and I did not catch it in PR #16

**Comment by tekktrik** [comment]
No you're right, I think the `a` is a typo that I carried over from the issue I made, I think.  I can fix that.  Good catch!

**Comment by jposada202020** [comment]
Changes look good. Thank you :)

**Review by jposada202020 — APPROVED** [review]
:) Thanks

**Pull request merged**
